### ISSUE TITLE
Borked in MP

### ISSUE THREAD

**Issue by MarshmallowFluf** [bbborbo/LasyBastardEngineer#1]
what i assume is extraneous code from when this was going to be a skills mod prevents this from acting like a basic skin mod, making it required by all parties if they want to use it in any capacity. if you want to add the skills, i'd suggest making another mod, or having a lazybastard lite for just the skin.

also, maybe change the unlock requirements/remove it altogether? that parts definitely optional though

**Comment by bbborbo** [comment]
forgor to close but thank you <3
